### ISSUE TITLE
'Open' times out waiting for a response

### ISSUE THREAD

**Issue by hohonuuli** [jaywardell/SharktopodaTest#2]
I wrote a simple client in Java to test the connection. It sends an open command like:

```json
{"command":"open", 
"url":"file:/Volumes/LBD2/i2map/2015-06-15_Test_Dives_4.mov", 
"uuid":"eabad378-d3a1-4a9b-b474-5b8911eaf71a"}
```

Sharktopoda opens the file. But __my client times out waiting for a response.__ 

Is Sharktopda responding via the same UDP connection or is it sending the  a response to the remote apps UDP? (The one that is configured using `connect`?). It should respond directly. 

For my reference . This is the code snippet in Java:

```java

// args: DatagramPacket packet, int sizeBytes, VideoCommand command
byte[] msg = new byte[sizeBytes];
DatagramPacket incomingPacket = new DatagramPacket(msg, msg.length);

DatagramSocket s = getSocket();
s.send(packet);
s.receive(incomingPacket);    // blocks until returned on timeout

int numBytes = incomingPacket.getLength();
byte[] response = new byte[numBytes];
System.arraycopy(incomingPacket.getData(), 0, response, 0, numBytes);
```

**Comment by hohonuuli** [comment]
I run into the same issue with `request status`. __Can you verify how Sharktopoda is responding?__ Is it using the regular client-server response on its own UDP port, or it responding via the remote apps port?

**Comment by jaywardell** [comment]
right now, it sends responses on port 3000.  I've had to respond on a different port than I receive on since I've been testing on a single machine.  I can't have 2 apps bound to the same port on one machine.  Of course, your setup doesn't have that problem.  

Try the branch at https://github.com/jaywardell/SharktopodaTest/tree/temporary_reponse_fix and see if that works for you (it won't for me yet).

**Comment by hohonuuli** [comment]
OK, first off. Things are looking really good. Nice work so far.

I tried the `temporary_response_fix` branch. No change; I still get timeouts. 

Not sure what your experience is with UDP, so I apologize if you already know this. But just to clarify, when Sharktopoda has an open UDP port, it should be able to receive and respond to messages using only that port. Right now I have 4 apps running simultaneously on the same machine as Sharktopoda sending it messages. (Just for testing, that's not a real world use)

Let's completely ignore the remote apps socket for the moment. My testing is stalled until this part is working. 

I'm off for the evening. I'll check in over the weekend. Let me know when this is working and I'll run more testing. 

Thanks for you work. Have a great weekend.

**Comment by jaywardell** [comment]
Have you been able to have two apps on the same machine both listen on the same port?  I'll continue to play around, but that's my hangup.  If SHarktopda sends and receives on, say, port 4000, then a client app on the same machine can't listen on port 4000 for a response, since it can't bind to that port.  I'll admit, UDP is new to me, which is one of the reasons I took on this project, but I don't know of a way around that yet.

I'm going to keep working on fixing this.  You're right, you can't test anything hardly until this is working.

**Comment by hohonuuli** [comment]
The client doesn't bind to that port. It just sends a message to it. Think of it like a webserver (in this case Sharktopoda) and a browser (remote apps). The webserver binds to port 80. But clients can send requests to and receive responses from a webserver via port 80, even on the same machine.

**Comment by jaywardell** [comment]
Okay, I think I may have it figured out.  Will post a possible fix in an hour or so...

**Comment by jaywardell** [comment]
Okay, try https://github.com/jaywardell/SharktopodaTest/tree/better_responses and let me know if that works for you.  If not, let me know what SharktopodaTest's log looks like (command-L in SharktopodaTest)

**Comment by hohonuuli** [comment]
Yea! Much better. The request/respsonse is working.

OK, one thing to watch for is that you correctly convert NS objects to strings. For request status I get the following back:

```json
{"response":"request status","status":"playing","uuid":"<__NSConcreteUUID 0x608000429740> 8A2A30F9-7507-4051-A18D-F39EF5135270"}
```

It should be:

```json
{"response":"request status","status":"playing","uuid":"8a2a30f9-7507-4051-a18d-f39ef5135270"}
```


### Lowercase Required by Spec

Note that the [international spec](http://www.itu.int/rec/T-REC-X.667/en) states:

> 6.5.4 Software generating the hexadecimal representation of a UUID shall not use upper case letters. NOTE – It is recommended that __the hexadecimal representation used in all human-readable formats be restricted to lower-case letters__. Software processing this representation is, however, required to accept both upper and lower case letters as specified in 6.5.2.

**Comment by jaywardell** [comment]
okay, I merged the changes into the master branch and took care of the NSUUID issue.

**Comment by hohonuuli** [comment]
Thanks. Much better! 

I noticed that the play and pause commands are returning a status response. That's OK. It's not in the REQUIREMENTS, but I'll modify the requirements to include them. I would make a change though so that the response to play and pause also includes the UUID.

That's all the testing I'll be doing today. Everything is coming along nicely. I'm very, very happy with the progress you've made. I probably won't do more testing until Monday. I'll also start digging into the code in Sharktopoda more then too. Have a great weekend.

**Comment by hohonuuli** [comment]
Just attaching some debug output from a small test program for my records.
[shark_debug.txt](https://github.com/jaywardell/SharktopodaTest/files/440884/shark_debug.txt)
