### ISSUE TITLE
Add "Close" command

### ISSUE THREAD

**Issue by hohonuuli** [jaywardell/SharktopodaTest#3]
Jay, I forgot to include a close command in the requirements. I added it to [https://github.com/underwatervideo/Sharktopoda/blob/master/REQUIREMENTS.md](https://github.com/underwatervideo/Sharktopoda/blob/master/REQUIREMENTS.md).

**Comment by jaywardell** [comment]
I posted this in between working on Issue #4.

**Comment by hohonuuli** [comment]
Confirmed that close command is working.
