### ISSUE TITLE
Show command has no effect on z order

### ISSUE THREAD

**Issue by hohonuuli** [jaywardell/SharktopodaTest#6]
Hey Jay,

The 'show' command should bring the appropriate window to the front of the other Sharktopoda windows. It doesn't seem to be doing that.

**Comment by hohonuuli** [comment]
Whoops. Never mind. There was bug on my end. Show is working fine.

**Comment by jaywardell** [comment]
good, cause I was at a loss.

**Comment by hohonuuli** [comment]
Sorry about the false alarm
